name: study_planner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.1.2
  pdf: ^3.11.1
#  path_provider: ^2.1.4
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.7
  fl_chart: ^0.70.2
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  table_calendar: ^3.1.2
  http: ^1.2.1
  google_generative_ai: ^0.4.0 # For Gemini API
  flutter_markdown: ^0.7.0     # For formatted AI responses
  sqflite: ^2.3.0   # For SQLite database
  path: ^1.9.0
  file_picker: ^8.0.0
  path_provider: ^2.1.0
  pdfrx: ^2.2.24 # pdf reader when ever wants to remove Functionality remove pfd reader.dart and book_notes.dart


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
